### ISSUE TITLE
Bootstrap Android project

### ISSUE THREAD

**Issue by decentralgabe** [TBD54566975/ssi-sdk-mobile#25]

**Comment by shamilovtim** [comment]
> I would very much like to see this!
> 
> From the repo, ReactNative is assumed. Is that correct? Is it possible to use Flutter too? An example app would go a long way. 😄

Hey @haarts! We have an example Android project here (in progress): https://github.com/TBD54566975/ssi-sdk-mobile/tree/main/react-native-ssi/android. It's not exhaustive, in the sense that it doesn't have a UI right now. It uses a react native wrapper over our Android SDK. We have support for native android, react native and plan to add support for Flutter as well!

**Comment by haarts** [comment]
Would Flutter support be hard to add?
Not burdened by any practical knowledge it seems one can generate an AAR and call these functions from Java(kotlin?), what then remains is using the Flutter channels to communicate with that Java code?

**Comment by shamilovtim** [comment]
> Would Flutter support be hard to add? Not burdened by any practical knowledge it seems one can generate an AAR and call these functions from Java(kotlin?), what then remains is using the Flutter channels to communicate with that Java code?

Yes if you use the native Android AAR you can begin adding a flutter wrapper to your project. however just keep in mind that this is in active development (not even alpha) so there are breaking changes constantly and can't be used for much yet
